CONNECTOR_PROTOCOL=quic
SERVER_LIST_ENDPOINTS=https://raw.githubusercontent.com/rd-lumi/fetch-list/refs/heads/main/production/main.txt,https://api-storage-staging.gofa.vn/relay-cloud/production/main.txt,https://relay-source-list.lumi.biz/production/main.txt
RELAY_BIP32_FILE=/etc/config/bip32_key.json
CERT_PATH=/relay-agent/tunnel.cert
SELECT_AGENT_FIX_THRESHOLD=50
SELECTOR_SERVER_INTERVAL=120,300
ENABLE_REROUTE=false
ALLOW_QUIC_INSECURE=true
